# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 20:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodorder', '0002_product_food_order_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='create date')),
                ('checked_out', models.BooleanField(default=False, verbose_name='checked out')),
                ('check_out_date', models.DateTimeField(verbose_name='check out date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_order_size', models.CharField(choices=[('Li', 'Lille'), ('St', 'Stor')], default='Lille', max_length=5)),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='foodorder.Cart', verbose_name='cart')),
            ],
        ),
        migrations.RemoveField(
            model_name='completed_order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='food_order_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.DeleteModel(
            name='Completed_order',
        ),
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='foodorder.Product', verbose_name='product'),
        ),
    ]
