# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodorder', '0003_auto_20170906_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='large_product_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Stor Produktpris'),
        ),
        migrations.AlterField(
            model_name='product',
            name='small_product_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Lille Produktpris'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Produkt Navn'),
        ),
    ]
