# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodorder', '0004_auto_20170906_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Produkt Navn'),
        ),
    ]
