# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodorder', '0005_auto_20170906_2039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Order',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='item',
            name='food_order_size',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AddField(
            model_name='item',
            name='large_order_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='large_order_quantity'),
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='foodorder.Order', verbose_name='order'),
        ),
        migrations.AddField(
            model_name='item',
            name='small_order_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='small_order_quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='large_product_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Stor Produktpris ( hvis ikke ledig, skriv 0.00 )'),
        ),
    ]
