# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodorder', '0006_auto_20170910_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nr',
            field=models.PositiveIntegerField(default=1, verbose_name='nr'),
        ),
    ]
