# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodorder', '0007_product_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='large_order_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Large order quantity'),
        ),
        migrations.AlterField(
            model_name='item',
            name='small_order_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Small order quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='large_product_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Large price ( if none, enter 0.00 )'),
        ),
        migrations.AlterField(
            model_name='product',
            name='small_product_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Small price'),
        ),
    ]
