# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodorder', '0009_auto_20170910_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Produktets aktiv status'),
        ),
    ]
