# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 23:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodorder', '0014_auto_20171005_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterorder',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
